---
machine_name: php-dev
mounts:
  - host: ../src
    client: /host_project
    loop_mount: /vhosts/web
#    loop_mount:
#    uid: 1000 # default
#    gid: 1000 #default
#    owner: vagrant #defautl
#    group: vagrant #default

mysqldump:
  - db_name: db1
    output: /host_project/db
  - db_name: db2
    output: /host_project/db



